### ISSUE TITLE
[BUG] - setOnSetImageUriCompleteListener can't use lambda form anymore for the interface OnSetImageUriCompleteListener

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [CanHub/Android-Image-Cropper#102]
- Lib Version [e.g. 1.1.0]
 2.3.0

**Describe the bug**
When it was in Java, I could use :

```
cropImageView.setOnSetImageUriCompleteListener { _, _, error ->
...
```

Now I have to use :

```kt
cropImageView.setOnSetImageUriCompleteListener(object : CropImageView.OnSetImageUriCompleteListener {
    override fun onSetImageUriComplete(view: CropImageView, uri: Uri, error: Exception?) {

```

**To Reproduce**
1. Just try the code I wrote above, of before this version and after.

**Expected behavior**
Should still allow to do it.

**Screenshots**
No need

**Smartphone (please complete the following information):**
None.

**Additional context**
I think whoever converted to Kotlin didn't look enough at the resulting code...
To fix this, I think it's possible to use "fun interface" instead of just "interface". This should be added for each interface in the project that has a single function.

**Comment by Canato** [comment]
Thanks for pointing this, for sure is an improvement we can do it. 

We didn't when we convert from Java because this would change the method notation, right know the difference is from using lambda to usage of creating the Listener class. 

If we decide to use the Kotlin we don't need to define an interface anymore, I mean the code `interface OnSetImageUriCompleteListener` doing this we need to be sure that Java and Kotlin keep working. 

Was not that we didn't look enough, the library was not update since 2018 there was a lot of bugs and fixes to put in place we cannot do all at once. So we decide to not break.

Please feel free to join us and drop a PR. This would be an amazing momento to create the `Java Sample code`, so we can test this changes. Probably the version `3.0`

**Comment by AndroidDeveloperLB** [comment]
@Canato I didn't mean I wrote in Java. this is in Kotlin.
When the library is in Java, it allows Kotlin (and Java) developers to use the shorter form.
All you need to do is to add "fun" for this interface (and others) in Kotlin, when possible.

**Comment by Canato** [comment]
Sorry, maybe I was confusing on my worlds. I meant we need to keep the library working for Kotlin and Java after the changes. So we need to test, something simple. 

Same as the other ticket, for sure is something we should do and something I want to do, but this is low on my priority now.
I try to order: Samples (so we can test), refactor, fixing bugs, dealing with deprecation, adding very asked features, improve in general (lamba/comments/doc/etc)

But feel free to add it ^^

**Comment by AndroidDeveloperLB** [comment]
OK here:
https://github.com/CanHub/Android-Image-Cropper/compare/main...AndroidDeveloperLB:main

**Comment by AndroidDeveloperLB** [comment]
Seems now it's possible again to use the short form again. Weird that the IDE doesn't suggest it though.
