### ISSUE TITLE
Multiple image crop

### ISSUE THREAD

**Issue by Mehdi-android** [CanHub/Android-Image-Cropper#127]
Is your feature request related to a problem? Please describe.
My project requirement is to upload multiple images to the server. Now with this library, I can only select one image at a time & then select another image & so on. 

Describe the solution you'd like
Can we have multiple image selections and after selecting we can crop one after another like instagram.

**Comment by Canato** [comment]
Hello @Mehdi-android please edit the description with some more information

> **Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

> **Describe the solution you'd like**
A clear and concise description of what you want to happen.

> **Describe alternatives you've considered**
A clear and concise description of any alternative solutions or features you've considered.

> **Additional context**
Add any other context or screenshots about the feature request here.

_Obs if you have some code for it, feel free to assign yourself open the PR after this issue_

**Comment by Mehdi-android** [comment]
> Hello @Mehdi-android please edit the description with some more information
> 
> > **Is your feature request related to a problem? Please describe.**
> > A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> > **Describe the solution you'd like**
> > A clear and concise description of what you want to happen.
> 
> > **Describe alternatives you've considered**
> > A clear and concise description of any alternative solutions or features you've considered.
> 
> > **Additional context**
> > Add any other context or screenshots about the feature request here.
> 
> _Obs if you have some code for it, feel free to assign yourself open the PR after this issue_

I have updated my question.

**Comment by Canato** [comment]
Thanks for updating!

Indeed, we could do something like this, would be amazing!

Please feel free to drop a PR with this feature.
