### ISSUE TITLE
How do i send intent only to camera if user denied external storage permission?

### ISSUE THREAD

**Issue by lightstudioapp** [CanHub/Android-Image-Cropper#147]
Is there any feature in this library which sends intent only to camera if user denied other permissions but accepted camera permission?

**Comment by Canato** [comment]
Hey @lightstudioapp I will change this issue to a discussion Q&A.

To answer you, in previous version of Android (9,8,7...) we need the external storage permission to crop the image, since we need to save the cropped somewhere. To the new versions (10,11,+) we can use scope storage. 

Based on this, the library do not expect to work only for the latest versions so we need the permission access.

That said, yes, we could have an option to select what will be showed to the user when choosing and image: Gallery/docs/camera.

If you feel like doing it please drop a PR with the code changes and we can merge =)
