### ISSUE TITLE
[Feat] - Set Image Quality

### ISSUE THREAD

**Issue by Rizza-Rabe** [CanHub/Android-Image-Cropper#152]
May i request to add a feature that can change the image quality of the image cropped. That would amazing to all of ur supporters. ❤️❤️

**Comment by Canato** [comment]
Hey Rizza, thanks for all the involvement in the library.
Sometime the work can get overwhelm and since is a free work is nice to have things organised!!! 

That's the mean reason we spent time with templates, automation, etc
**Please follow the repository template for features:**

> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 
> _Obs if you have some code for it, feel free to assign yourself open the PR after this issue_

Close because if out of template format.
