### ISSUE TITLE
[hacktoberfest] - image pick option

### ISSUE THREAD

**Issue by Canato** [CanHub/Android-Image-Cropper#226]
## Description
Today the user can use the library to pick images from camera, gallery or documents

But the user cannot select that is from camera only, for example. So we need to add a parameter to the contract that define which intents we will use for selection.

## Possible solution:
`PickImageContract` would receive a data class, like we have in `CropImageContract` and this data class will contain booleans for each type of selection camera/gallery/etc in the case that if you only choose one it open directly

**Comment by jashasweejena** [comment]
Hey, I would like to work on this

**Comment by Canato** [comment]
Thanks @jashasweejena feel free to start.

**Comment by jashasweejena** [comment]
Thank you @Canato :) !

**Comment by Zikstar** [comment]
Hi @Canato, I don't know how large the scope of this work will be. But I'll like to help out with this, or writing UI tests

**Comment by Canato** [comment]
Hey @Zikstar any help will be amazing! Try and let me know

**Comment by Zikstar** [comment]
I've started working on it @Canato . Do you also want users to be able to specify where they want to pick from as part of CropImageContractOptions? That way in the CropImageActivity, its not a hardcoded value
Something like what I have in the screenshot below

<img width="507" alt="Screen Shot 2021-10-05 at 14 05 01" src="https://user-images.githubusercontent.com/16862777/136078343-37abee58-e510-4b51-af9c-7fb360b7093b.png">
.

**Comment by Canato** [comment]
Yes @Zikstar nice approach, we probably need to update `options` to `cropImageOptions` and I expected that our `PIckImageOptions` will have some default value that always show camera and gallery, giving the user the option to update.

**Comment by Zikstar** [comment]
Cool I'll update that @Canato

**Comment by jashasweejena** [comment]
Hey @Canato @Zikstar, I was actually working on the same issue.

**Comment by Canato** [comment]
@jashasweejena can keep working, already saw some PRs that are open and after people find bugs they do not fix, because some stuffs in this library are hard.

If one of you merge before the other, for sure we will have improvements from the second person to put on top of it!

I believe we can bring a good solution together and everyone will be able to help and get some hactoberfest points ^^

**Comment by jashasweejena** [comment]
Cool @Canato ^_^

**Comment by jashasweejena** [comment]
Hey @Canato, as it appears that @Zikstar has made some good progress on the issue I don't think it makes sense for me to work on this issue. Is there any issue you'd want me to look into?

**Comment by Canato** [comment]
Sorry for the messup @jashasweejena feel free to check what Zikstar already did and think about improvements or think in any of the other [issues we have open](https://github.com/CanHub/Android-Image-Cropper/issues?q=is%3Aopen+is%3Aissue+label%3Ahacktoberfest) 

Tests and documentation and never enough ^^

**Comment by Zikstar** [comment]
Sorry to barge in @jashasweejena. This is actually my first open-source contribution, and it's a library I'm familiar with and use at work.

**Comment by jashasweejena** [comment]
Sure @Canato. No problems @Zikstar, I'm glad that you completed your first contribution. I'm a rookie myself and I know it feels awesome ☺️

**Comment by Zikstar** [comment]
@Canato How do I update wiki? Is that in the code or on github?

**Comment by Zikstar** [comment]
Finally, is it fair to say that "Gallery" is a subset of "Documents" based on this?
<img width="671" alt="Screen Shot 2021-10-05 at 16 11 13" src="https://user-images.githubusercontent.com/16862777/136096632-2279b5ad-40ee-455d-bade-2eb727f33270.png">
Because in that case my logic will be,
-  if both includeGallery and includeDocuments are false - add nothing
- if includeDocuments is true, it doesn't matter what gallery is : add Documents 
- if includeDocuments is false, and includeGallery is true: add Gallery

**Comment by Canato** [comment]
I saw the PR before this comment, sorry. 

> Finally, is it fair to say that "Gallery" is a subset of "Documents" based on this?

We should not assume this if we can split 🤔 maybe using something more specific over `*/*` but not sure.
If is to hard, let's make as subset and let is clear on the code somehow (documentation and name of the variables)

**Comment by Zikstar** [comment]
So, just looked into mime types, its not possible to use anything more specific, because the results would be irrelevant to images. The other specific mime types are video/*, text/*, audio/*. It has to be a subset. And I can reflect that in the variable names("includeAllDocuments and includeOnlyGallery"). And maybe the documentation can reflect that if you set includeAllDocuments to true, you don't need to set includeOnlyGallery. Another option would be to remove "includeAllDocuments" completely, because any relevant applications will always be caught by image/* anyway. And includeDocuments is always set to false  in the library anyway
