### ISSUE TITLE
[BUG] - Image crop not work got the Full size image in Android 11

### ISSUE THREAD

**Issue by Gauravyadav101** [CanHub/Android-Image-Cropper#238]
🚨🚨 Before open the ticket please check if you can reproduce the bug in the sample code

 - Lib Version [e.g. 1.1.0]
 - 3.3.5
 
**Describe the bug**
When I am open cmera and gallery from both place crop not work means i am getting original size image in Android 11

I am using java Code :

   Uri tempUri = Uri.fromFile(new File(path));
        CropImage.activity(tempUri)
                .setGuidelines(CropImageView.Guidelines.ON)
                .setBorderLineColor(Color.parseColor("#FF7A2A"))
                .setGuidelinesColor(Color.parseColor("#696969"))
                .setAllowRotation(true)
                .start(mActivity);

**To Reproduce**

**Expected behavior**

**Media**
Please add screenshots and/or screen recordings to help explain your problem.
We cannot help without more information

**Smartphone (please complete the following information):**
 - Device: [e.g. Pixel 3XL]

**Additional context**

**Comment by Canato** [comment]
When you opened this issue you said was version `3.3.5` of this library, but you just update now.
### So this issue is not valid and I will close it, please open issues with the complete information so I can help better =)

-------
@Gauravyadav101 you have many unnecessary code in your sample

Please check the [Java Sample](https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/java/com/canhub/cropper/sample/crop_image_java/app/SCropImageFragmentJava.java) implementation we have and use the library like suggested in this file.

Suggestion to use the method `startCameraWithoutUri()` as North, where you let the library pick the image and return the value 
```java
private final ActivityResultLauncher<CropImageContractOptions> cropImage =
            registerForActivityResult(new CropImageContract(), presenter::onCropImageResult);
```

Where `presenter::onCropImageResult` is how you handle the answer, like:
```java
public void onCropImageResult(@NonNull CropImageView.CropResult result) {
        if (result.isSuccessful()) {
            view.handleCropImageResult(result.getUriContent().toString().replace("file:", ""));
        } else if (result.equals(CropImage.CancelledResult.INSTANCE)) {
            view.showErrorMessage("cropping image was cancelled by the user");
        } else {
            view.showErrorMessage("cropping image failed");
        }
    }
```

etcs
