### ISSUE TITLE
why need camera permission for using only gallery picker

### ISSUE THREAD

**Issue by hasanZolfagharipour** [CanHub/Android-Image-Cropper#270]
Hi
There are two issue with permissions. First of all, Why need camera permission to using this library only for picking image from gallery.
And second, is there any way to use benefits of ActivityResultContracts.TakePicture to take picture and edit it without any permissions ?

**Comment by Canato** [comment]
Hey @hasanZolfagharipour =D welcome. You are not following the template for issues, but will convert this in a discussion, since this are more like questions, let me try to answer and if we spot something wrong we can open an issue ^^

> First of all, Why need camera permission to using this library only for picking image from gallery.

We do not request camera permission directly, we just ask for `READ` and `WRITE`
```kt
<manifest>
   <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
   <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"
       android:maxSdkVersion="28" />
</manifest>
```

But indeed you are right we need this permission on our code. Until a month ago we could not disable the camera pick, so was intrinsic to the usability of the library, now that we can disable it we need to update the code.
Please feel free to drop a PR with this changes =D 

> And second, is there any way to use benefits of ActivityResultContracts.TakePicture to take picture and edit it without any permissions ?

Without any permission no =/, you need at least a couple and depending on the OS versions too.
- Until android 4 you don't need camera permission
- Until android 9 you need all permission `camera/read/write` (we keep this because some OSs in some devices has bugs if we try to use scope storage)
- Android 10+ we need `CAMERA` direct permission on manifest (user is not prompt with anything) and `READ` permission for gallery. We descope `WRITE` permission for scope storage

As you can see is a little of a dance to keep all working for all versions, but feel free to drop a PR to improve this ^^
