### ISSUE TITLE
[Feat] - Add an Intent Chooser as an alternate to current Alert Dialog to choose image source

### ISSUE THREAD

**Issue by Devenom1** [CanHub/Android-Image-Cropper#325]
I've like the way you've maintained this library. I have added an alternate to choose the image source. You currently have and AlertDialog to choose from Camera or Gallery apps. I would like to add an intent chooser as an alternate. It seems to be working well on all android versions I've tested it on so far.

I'll add a PR for it

**Comment by Canato** [comment]
Thanks =D!

We make this change because of the bugs we have related to MIUI (Xiaomi)
1. [PR](https://github.com/CanHub/Android-Image-Cropper/pull/275)
1. [BUG - MIUI (Xiaomi) cant pick image from gallery](https://github.com/CanHub/Android-Image-Cropper/issues/253)
1. [BUG - FileUriExposedException when trying to lunch only camera intent](https://github.com/CanHub/Android-Image-Cropper/issues/274)

_+ (Not following the templates, but the same issue about MIUI)_
- [Issue](https://github.com/CanHub/Android-Image-Cropper/issues/249) 
- [Issue](https://github.com/CanHub/Android-Image-Cropper/issues/248) 
- [Issue](https://github.com/CanHub/Android-Image-Cropper/issues/238) 
- [Issue](https://github.com/CanHub/Android-Image-Cropper/issues/219)

We need to be sure this is fixed and/or give the user the option to use `intent chooser` instead of default Alert Dialog

**Comment by Devenom1** [comment]
I have been checking the issues you mentioned above. I'm not sure I've managed to fix all these issues. 

Our apps have between 5k-20k users as of now. In one of our apps the ArthurHub version of the library that I modified is used a lot. This app is mostly being used by users with Mi, Vivo, and Oppo phones. We have a close interaction with these users and we've faced a lot of issues you've mentioned above.

I've managed to make fixes for most of these issues mentioned above. I myself have an Mi Phone (MIUI) running Android 11 and I've tested it using someone else's phone that had MIUI and Android 12. Also all our users with Mi, Vivo, Oppo and other Chinese brands have been uploading images using my modified library without any issue.

There's no optimal way to check if the issues are 100% resolved but I feel most of them are.

Could we maybe find a way to keep the intent chooser optional? And if any issues come by we can try and fix them

**Comment by Canato** [comment]
> Could we maybe find a way to keep the intent chooser optional? And if any issues come by we can try and fix them

Yes, I think this is the best option. So who prefer Intent Chooser can select ir

**Comment by Devenom1** [comment]
Alright. Awesome @Canato I will try and make that an option. I will also update the required documentation you mentioned in the PR. If you have any tech input about how we can keep this intent chooser optional without changing much of the code it would be great. I'll still try to find a good way to do it

**Comment by Canato** [comment]
> If you have any tech input about how we can keep this intent chooser optional without changing much of the code it would be great.

I believe the easy solutions is a simple Boolean option for AlertDialog or Default intent into the library options, like we have for skip PR you did 

If you want, you can make both in the same PR, just need 2 changelog entries. Or we can keep split

**Comment by Devenom1** [comment]
Alright. I'm reworking the intent chooser code as per your suggestion. Will try to get it live asap
