### ISSUE TITLE
[BUG] - Taking front camera photo flips image

### ISSUE THREAD

**Issue by nejcburic** [CanHub/Android-Image-Cropper#374]
- Lib Version 4.2.1
 
**Describe the bug**
When taking photo from front camera it flips image horizontally.

**To Reproduce**
1. Go to sample app
2. Click on 'Call library directly without uri'
3. Choose 'Camera'
4. Switch to front camera
5. Take photo
6. Image is flipped horizontally

**Expected behavior**
When I take photo from front camera I expect it to be the same as in camera preview, not flipped horizontally.

**Media**
Take a custom selfie.

**Smartphone (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12

**Additional context**
No additional context.

**Comment by Canato** [comment]
@nejcburic could you please share a video? What I'm seen is the phone camera flipping the image and not the library 🤔

**Comment by nejcburic** [comment]
@Canato here is the video. Yes I think phone camera is flipping the image. Can I actually prevent that from happening?

https://user-images.githubusercontent.com/84720288/171158912-1a7e1e62-1f11-4a7b-8c65-be172e61033a.mp4

**Comment by Canato** [comment]
This will be interesting because not all cameras flip. So I believe can depend on brand/os, etc

I will take a look next week (long holidays coming here), but the library has a flip horizontal feature. That you can enable while cropping `setAllowFlipping(true)`... so the user decides when to do it. Or you can call it directly and make it flips `setFlipHorizontally(true)`

Because maybe not all your users will have it flipped 🤔

**Comment by nejcburic** [comment]
well if flipping is camera problem then you can close the issue. Thanks for checking out.

**Comment by Canato** [comment]
Let me know if I can help in other way =D
