### ISSUE TITLE
[BUG] - Toolbar is not showing

### ISSUE THREAD

**Issue by kingnightdrifter** [CanHub/Android-Image-Cropper#433]
- Lib Version [e.g. 1.1.0]
 
**Describe the bug**
Toolbar is not showing if my activity theme is NoActionbar

**Comment by Canato** [comment]
Hey @kingnightdrifter welcome to the repository, believe we have this solved. 

on the README we have a FAQ

This look like to be the first question of the [FAQ](https://github.com/CanHub/Android-Image-Cropper/blob/main/.documentation/FAQ.md#cant-see-the-crop-button-so-cant-crop-the-image)

If this is not the case try to search for similar situations, one of these can help you probably.

![Screenshot 2022-09-05 at 12 12 26](https://user-images.githubusercontent.com/15942449/188436119-89d44605-f61c-44c2-bc42-f36a64d7d1ee.png)
![Screenshot 2022-09-05 at 12 11 56](https://user-images.githubusercontent.com/15942449/188436123-8bbfbb90-5f75-422b-bea2-dcecdbaf78b3.png)

**Comment by hiteshsarsava** [comment]
@Canato Atleast Add some example to roll own activity. Also Add disclaimer in notes with Bold Letters. I wasted 2 hours for this. Because I am using No Action bar Activity Theme in App. Now these days all the devs using this practice.

**Comment by Canato** [comment]
> @Canato Atleast Add some example to roll own activity. Also Add disclaimer in notes with Bold Letters. I wasted 2 hours for this. Because I am using No Action bar Activity Theme in App. Now these days all the devs using this practice.

Hey @hiteshsarsava Thanks for participating in the repository.

Since this is a volunteer repository maintained without any value for who code on it sometimes is hard to maintain all this examples and code in place.
Hopefully we can expect that people will take the time to read the sample codes and look for previous issues.
2h is not a waste if you are learning, IMHO, normal stuff

I would invite you to take time and open a PR with the suggestions you believe to be valuable for the repository and future users. 

We have this Sample code: https://github.com/CanHub/Android-Image-Cropper/blob/main/sample/src/main/kotlin/com/canhub/cropper/sample/SampleCustomActivity.kt

That uses
```kt
    <activity
        android:name="com.canhub.cropper.sample.SampleCustomActivity"
        android:theme="@style/Theme.SampleNoActionBar"/>
```

Feel free to add and modify in a way that will help more people and would have help you =)
