### ISSUE TITLE
maximum zoom capability

### ISSUE THREAD

**Issue by mgood7123** [CanHub/Android-Image-Cropper#64]
is this capable of zooming to a pixel by pixel zoom level? eg where each individual pixel is visible?

**Comment by Canato** [comment]
Hey @mgood7123 thanks for the question! I will move this to Discussions instead of issues, so we can keep the discussion there!


About your question:
You can set:
```
CropImage.start(..)
    .setMaxZoom(99999) // This will put or Max Zoom in maximum
    .setAutoZoomEnabled(true) // This will help the zoom navigation/gesture
    .setMinCropWindowSize(1, 1) // This will be the minimum size for the crop window
    .setMinCropResultSize(1, 1) // This will guarantee 1dp width and 1dp height
    .start(..)
```

So the library can guarantee 1dp of precision, but to know the relation between the 1dp and how many pixels it has, you will need to convert based on the device screen.

Obs: the quality of the picture need to be really high to have a great zoom crop
