### ISSUE TITLE
Cannot get path From URI. Uri lacks 'file' scheme

### ISSUE THREAD

**Issue by widianapw** [CanHub/Android-Image-Cropper#83]
Uri lacks 'file' scheme: content: //packagename.cropper.fileprovider/my_images/Pictures/imagename.jpg
I cannot Get path from URI

**Comment by Canato** [comment]
Hey @widianapw sorry for the long time to reply I'm on holidays this weeks, so less in my laptop.

Could you be more explicit? 
- Which version of the lib?
- How to reproduce using thew sample code?
- Which method are you using? (there is 3 ways of using the library)
- Do you have any code or logs?
- What would be the expectation?

Thanks.

**Comment by widianapw** [comment]
Hallo @Canato 
i use the latest version (2.2.1)

i came here because camera on ravindu's lib is not working on android 11.

my code to start crop activity
```
private fun openImageResource() {
        CropImage.activity()
            .setGuidelines(CropImageView.Guidelines.ON)
            .setAspectRatio(1,1)
            .start(this)
    }
```

**the comparison**
Uri I get from  ravindu
`file:///data/user/0/com.example.cloudinaryimageupload/cache/cropped3592952233873349951.jpg`

Uri i get now
`content://com.example.cloudinaryimageupload.cropper.fileprovider/my_images/Pictures/cropped1347220270430465128.jpg`

I need to get the file path because i need to upload it to the cloudinary.
but the image's path from uri i got is always not found.

is there any way to get the image path? because my project has been running..

Thanks

**Comment by Canato** [comment]
@widianapw 
Can you try to make a string change where you replace `content:` by `file:` ???

Because this path is exactly the Android 10 and Android 11 issue. 

The OS don't allow us to get external storage permission anymore. So we need to use Scope storage.

For sure you will need to update the logic in your code to get access if you want.

Or use the write storage permission and create a new path putting the image generated 


The new Android changes broke this logic, that's the reason we needed to change from "file" to "content". (In other words, change from external access to scope storage)

**Comment by RanjitPati** [comment]
The same issue I want to describe https://github.com/CanHub/Android-Image-Cropper/issues/84

**Comment by Canato** [comment]
> The same issue I want to describe https://github.com/CanHub/Android-Image-Cropper/issues/84

Like I said in the 84 thread, you didn't shared with us the code to create the file.

Android does not permit anymore the usage of external storage permissions.

That's the reason many libraries are breaking for OS 10 and 11.

Because of this the URI is a Scope storage (content://..) and this is the the file path anymore.

We update the library because of Android permission changes. Now the codes need to be updated too for the Android permissions

**Comment by AbdulmalekAlshugaa** [comment]
I have the same issue, can we get a sample of the latest implementation

**Comment by Canato** [comment]
@AbdulmalekAlshugaa you can check the sample app in this repository https://github.com/CanHub/Android-Image-Cropper/tree/main/sample it has 3 different ways of using the library with many scenarios =). Hope this help.

**About the issue:**
Now with OS 11, this behaviour changed so the library was updated, not we need to update the usage of it too.
Please let's put all discussion about this on the same place: https://github.com/CanHub/Android-Image-Cropper/discussions/87

Sadly this is an Android OS change, but if anyone know a better fix for the latest OS, using scope storage and keeping it `file` drop a PR cause will help everyone =)


I will close so we focus the discussion on the same place
https://github.com/CanHub/Android-Image-Cropper/discussions/87

**Comment by Canato** [comment]
Please try the latest `3.0.0` release and let me know
