### ISSUE TITLE
[Feat] - Free crop (not only rect or oval)

### ISSUE THREAD

**Issue by Laur89ro** [CanHub/Android-Image-Cropper#88]
Hello! I was wandering how difficult  it would be to add support for free cropping. Allow the user to choose the point for every corner. This is a feature i am really interested in and i would like to contribute, but i would like some feedback from someone who is familiar with this project.
Thank you!

**Comment by Canato** [comment]
This is an interesting feature. I believe we can achieve because the code define the 4 corners as X^Y positions.

Yet I see as a trick one! 
We need to define how many corners the use can have (we can start easy using 4 as default)
We need to be sure the touch areas for crop movement do not overlap
And the behaviour of zoom in/out when `.setFixAspectRatio(true)`  

But I would love to see some option like this! 
Sadly I cannot put as my personal ToDo now, cause there is many work to be done for stability (can check in project the next tasks in the roadmap) 
**But please, fell free to join the codebase and try the changes =D**

Hopefully we can have a new nice feature soon

If you are wiling to do this, think about [Join the Team](https://github.com/CanHub/Android-Image-Cropper/discussions/42) even for a small period of time =)

Observation: Maybe this issue will stale in 14 days, we will receive a bot notification, you can come here when this happens and give an update. The whole idea is to avoid any old forgoten ticket. When you open a PR for this I can `pineed`  this issue =)

**Comment by Laur89ro** [comment]
From what I can see to create the crop rectangle it uses a object RectF. It doesn't seem you can set 4 independent points

**Comment by Canato** [comment]
> From what I can see to create the crop rectangle it uses a object RectF. It doesn't seem you can set 4 independent points

Indeed, I was thinking about the touchable area, totally messed it on my mind, I'm out of my laptop until 22/3 (holidays) so coulnd't navigate in the code XD

**Comment by Laur89ro** [comment]
No problem. I will try to dig deeper into the code and see if i can find a solution. If you have any ideas please share :)
Thanks!

**Comment by omkar-tenkale** [comment]
Maybe this would help
https://github.com/igreenwood/SimpleCropView

**Comment by Laur89ro** [comment]
It doesn't. I don't want to crop a rectangle. I want to be able to select like a trapezium or rombus.
